# Generated by Django 5.1.2 on 2024-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, verbose_name='Ссылка')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year_start_production', models.IntegerField(verbose_name='Год начала производства')),
                ('year_end_production', models.IntegerField(verbose_name='Год окончания производства')),
                ('engine', models.CharField(max_length=50, verbose_name='Двигатель')),
                ('power_hp', models.IntegerField(verbose_name='Мощность в л.с.')),
            ],
        ),
    ]
