# Generated by Django 5.1.2 on 2024-10-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='version',
            field=models.CharField(max_length=50, null=True, verbose_name='Версия'),
        ),
    ]
