# Generated by Django 5.1.2 on 2024-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0002_car_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_index',
            field=models.CharField(max_length=10, null=True, verbose_name='Индекс кузова'),
        ),
    ]
