# Generated by Django 5.1.2 on 2024-11-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0003_car_body_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_displacement',
            field=models.FloatField(default=2.0, verbose_name='Объём двигателя'),
        ),
    ]
