# Generated by Django 5.1.2 on 2024-11-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0004_car_engine_displacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_index',
            field=models.CharField(max_length=10, verbose_name='Индекс кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_displacement',
            field=models.FloatField(verbose_name='Объём двигателя'),
        ),
    ]
