# Generated by Django 5.1.2 on 2024-11-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0005_alter_car_body_index_alter_car_engine_displacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='link',
        ),
    ]
