# Generated by Django 5.1.2 on 2024-12-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0006_remove_car_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug поле'),
        ),
    ]
