# Generated by Django 5.1.2 on 2024-12-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0008_engine_car_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_displacement',
        ),
        migrations.RemoveField(
            model_name='car',
            name='power_hp',
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(verbose_name='Вес в кг.'),
        ),
    ]
