# Generated by Django 5.1.2 on 2024-12-14 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legend_cars', '0009_remove_car_engine_remove_car_engine_displacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='legend_cars.engine', verbose_name='Двигатель'),
        ),
    ]
